# Generated by Django 3.1.4 on 2020-12-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipper_company_id', models.IntegerField(blank=True, null=True)),
                ('carrier_company_id', models.IntegerField(blank=True, null=True)),
                ('truck_id', models.IntegerField(blank=True, null=True)),
                ('co2_model_id', models.IntegerField(blank=True, null=True)),
                ('travelled_distance', models.FloatField(blank=True, null=True)),
                ('fuel_consumed', models.FloatField(blank=True, null=True)),
                ('estimated_fuel_consumed', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('type_of_goods', models.CharField(blank=True, max_length=128, null=True)),
                ('start_country', models.CharField(blank=True, max_length=128, null=True)),
                ('start_city', models.CharField(blank=True, max_length=128, null=True)),
                ('start_postcode', models.CharField(blank=True, max_length=128, null=True)),
                ('end_country', models.CharField(blank=True, max_length=128, null=True)),
                ('end_city', models.CharField(blank=True, max_length=128, null=True)),
                ('end_postcode', models.CharField(blank=True, max_length=128, null=True)),
                ('type_of_calculations', models.CharField(blank=True, max_length=128, null=True)),
                ('allocated_distance', models.FloatField(blank=True, null=True)),
                ('allocated_fuel', models.FloatField(blank=True, null=True)),
                ('total_co2_emitted', models.FloatField(blank=True, null=True)),
                ('creation_timestamp', models.DateTimeField(blank=True, null=True)),
                ('last_updated_timestamp', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'shipments',
                'managed': True,
            },
        ),
    ]
